version: "3.8"

networks:
  docker-tempo:
    name: "docker-tempo"

services:
  tempo:
    image: grafana/tempo:0.7.0
    command: [ "--config.file=/etc/tempo-local.yaml" ]
    volumes:
      - ./etc/tempo-local.yaml:/etc/tempo-local.yaml
    ports:
      - "6831:6831/udp"
      - "9411:9411"
      - "3100:3100"
      - "55680:55680"
      - "14250:14250"
    networks:
      - docker-tempo

  tempo-query:
    image: grafana/tempo-query:0.7.0
    command: [ "--grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml"]
    volumes:
      - ./etc/tempo-query.yaml:/etc/tempo-query.yaml
    ports:
      - "16686:16686"  # jaeger-ui
    networks:
      - docker-tempo

  grafana:
    build: './scripts/config/grafana'
    volumes:
      - ./data/grafana-data/datasources:/etc/grafana/provisioning/datasources
      - ./scripts/grafana:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    networks:
      - docker-tempo
    depends_on:
      - tempo-query

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./scripts/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./scripts/prometheus:/prometheus
    networks:
      - docker-tempo

